#! /bin/bash
# Created By: Dr. Russel Mason
# Edited By: Daniel W. Anner
# Date acquired: 11/04/2020
# Date last modified: 11/04/2020
# Gets a list of zip data from Indego Bike Rentals and downloads the listed zip URL's
# Useage: prompt$ ./acquire_clean_bikedata

if [ $1 == "debug" ]; then
    rm -rf ./data/*
fi

curl https://www.rideindego.com/about/data/ > bikewebdata
grep -E -o 'http.*\.zip' bikewebdata > urls
echo on

mkdir -p ./data/indego_zip
mkdir -p ./data/indego_extracted

readarray -t arr < urls

cd ./data/indego_zip
for i in "${arr[@]}"; do
    echo $i
    curl -O $i
done

find ./ -name "*.zip" -exec sh -c 'unzip -o -d "../indego_extracted/" "$1"' _ {} \;

cd ../indego_extracted/
find ./ -not -name '*.csv' -maxdepth 1 -exec rm -rf {} \; 2> /dev/null
for f in *\ *; do mv "$f" "${f// /_}"; done

cd ../..
rm bikewebdata urls
