---
title: "Firearms Data"
output: html_notebook
# Analysis of firearms data
# Daniel W. Anner 
---

```{r}
#install.packages(c("devtools", "tidyverse", "readr", "dplyr", "fiftystatr", "viridis", "mapproj", "ggpubr", "ggmap", "chron", "lubridate", "list", "ggthemes"))
library(devtools)
install_github("wmurphyrd/fiftystater")

library(tidyverse)
library(readr)
library(dplyr)
library(fiftystater)
library(viridis)
library(mapproj)
library(ggmap)
library(ggpubr)
library(chron)
library(lubridate)
library(list)
library(hrbrthemes)
setwd('/home/rstudio/dssa_workspace/R/Data Exploration Project/')
```

# Read in the data
```{r message=FALSE, warning=FALSE}
FirearmLicenses <- read_csv("data/federal_firearms_licenses_1975-2019.csv")
BackgroundChecks_2014 <- read_csv("data/firearm_background_checks_bystate_2014.csv")
BackgroundChecks_2015 <- read_csv("data/firearm_background_checks_bystate_2015.csv")
BackgroundChecks_2016 <- read_csv("data/firearm_background_checks_bystate_2016.csv")
BackgroundChecks_2017 <- read_csv("data/firearm_background_checks_bystate_2017.csv")
BackgroundChecks_2018 <- read_csv("data/firearm_background_checks_bystate_2018.csv")
HomicideData_2014 <- read_csv("data/MurderVictims-2014.csv")
HomicideData_2015 <- read_csv("data/MurderVictims-2015.csv")
HomicideData_2016 <- read_csv("data/MurderVictims-2016.csv")
HomicideData_2017 <- read_csv("data/MurderVictims-2017.csv")
HomicideData_2018 <- read_csv("data/MurderVictims-2018.csv")
```

#Helper function
```{r}
# Ref: https://5harad.com/mse125/r/visualization_code.html
addUnits <- function(n) {
  labels <- ifelse(n < 1000, n,  # less than thousands
                   ifelse(n < 1e6, paste0(round(n/1e3), 'k'),  # in thousands
                          ifelse(n < 1e9, paste0(round(n/1e6), 'M'),  # in millions
                                 ifelse(n < 1e12, paste0(round(n/1e9), 'B'), # in billions
                                        ifelse(n < 1e15, paste0(round(n/1e12), 'T'), # in trillions
                                               'too big!'
                                        )))))
  return(labels)
}
```

#Total firearms plot
```{r}
ggplot(FirearmLicenses, aes(x=year, y=total)) +
  theme_modern_rc() +
  geom_line() +
  geom_point() +
  scale_y_continuous(limits = c(0, 300000), breaks=seq(0, 300000, by = 50000)) +
  scale_x_continuous(limits = c(1975, 2020), breaks=seq(1975, 2020, by = 5)) +
  labs(x = "Year", y = "Firearm Licenses", title = "Firearm Licenses (1975-2019)")
ggsave("png/firearmlicenses_1975-2020.png")
```

#Summation Data
```{r}
paste(sum(FirearmLicenses$total), "in 1975 - 2019")
FirearmLicenses_1418 <- FirearmLicenses %>% filter(between(year, 2014, 2018))
paste(sum(FirearmLicenses_1418$total), "in 2014 - 2018")
```

#2014 Homicide Data by State
```{r, fig.width = 18} 
ggplot(HomicideData_2014, aes(x=state, y=total_firearms)) +
  theme_modern_rc() +
  geom_bar(stat="identity") +
  scale_y_continuous(limits = c(0, 1500), breaks=seq(0, 1500, by = 300)) +
  scale_x_discrete(label=state.abb) +
  labs(x = "State", y = "Firearm Deaths", title = "Firearm Related Homicides (2014)") + 
  theme(plot.title = element_text(size = 30), text = element_text(size=25), axis.text.x = element_text(angle=90, vjust=0.5, hjust=1, size = 18), axis.text.y = element_text(hjust=1, size = 18), axis.title.x = element_text(hjust = 1, size = 25, color = "#7C9488"), axis.title.y = element_text(hjust = 1, size = 25, color = "#7C9488"), plot.caption = element_text(size = 15))
ggsave("png/firearmhomicides-2014.png")
```

#2015 Homicide Data by State
```{r, fig.width = 18} 
ggplot(HomicideData_2015, aes(x=state, y=total_firearms)) +
  theme_modern_rc() +
  geom_bar(stat="identity") +
  scale_y_continuous(limits = c(0, 1500), breaks=seq(0, 1500, by = 300)) +
  scale_x_discrete(label=state.abb) +
  labs(x = "State", y = "Firearm Deaths", title = "Firearm Related Homicides (2015)") + 
  theme(plot.title = element_text(size = 30), text = element_text(size=25), axis.text.x = element_text(angle=90, vjust=0.5, hjust=1, size = 18), axis.text.y = element_text(hjust=1, size = 18), axis.title.x = element_text(hjust = 1, size = 25, color = "#7C9488"), axis.title.y = element_text(hjust = 1, size = 25, color = "#7C9488"), plot.caption = element_text(size = 15))
ggsave("png/firearmhomicides-2015.png")
```

#2016 Homicide Data by State
```{r, fig.width = 18}  
ggplot(HomicideData_2016, aes(x=state, y=total_firearms)) +
  theme_modern_rc() +
  geom_bar(stat="identity") +
  scale_y_continuous(limits = c(0, 1500), breaks=seq(0, 1500, by = 300)) +
  scale_x_discrete(label=state.abb) +
  labs(x = "State", y = "Firearm Deaths", title = "Firearm Related Homicides (2016)") + 
  theme(plot.title = element_text(size = 30), text = element_text(size=25), axis.text.x = element_text(angle=90, vjust=0.5, hjust=1, size = 18), axis.text.y = element_text(hjust=1, size = 18), axis.title.x = element_text(hjust = 1, size = 25, color = "#7C9488"), axis.title.y = element_text(hjust = 1, size = 25, color = "#7C9488"), plot.caption = element_text(size = 15))
ggsave("png/firearmhomicides-2016.png")
```

#2017 Homicide Data by State
```{r, fig.width = 18} 
ggplot(HomicideData_2017, aes(x=state, y=total_firearms)) +
  theme_modern_rc() +
  geom_bar(stat="identity") +
  scale_y_continuous(limits = c(0, 1500), breaks=seq(0, 1500, by = 300)) +
  scale_x_discrete(label=state.abb) +
  labs(x = "State", y = "Firearm Deaths", title = "Firearm Related Homicides (2017)") + 
  theme(plot.title = element_text(size = 30), text = element_text(size=25), axis.text.x = element_text(angle=90, vjust=0.5, hjust=1, size = 18), axis.text.y = element_text(hjust=1, size = 18), axis.title.x = element_text(hjust = 1, size = 25, color = "#7C9488"), axis.title.y = element_text(hjust = 1, size = 25, color = "#7C9488"), plot.caption = element_text(size = 15))
ggsave("png/firearmhomicides-2017.png")
```

#2018 Homicide Data by State
```{r, fig.width = 18} 
ggplot(HomicideData_2018, aes(x=state, y=total_firearms)) +
  theme_modern_rc() +
  geom_bar(stat="identity") +
  scale_y_continuous(limits = c(0, 1500), breaks=seq(0, 1500, by = 300)) +
  scale_x_discrete(label=state.abb) +
  labs(x = "State", y = "Firearm Deaths", title = "Firearm Related Homicides (2018)") + 
  theme(plot.title = element_text(size = 30), text = element_text(size=25), axis.text.x = element_text(angle=90, vjust=0.5, hjust=1, size = 18), axis.text.y = element_text(hjust=1, size = 18), axis.title.x = element_text(hjust = 1, size = 25, color = "#7C9488"), axis.title.y = element_text(hjust = 1, size = 25, color = "#7C9488"), plot.caption = element_text(size = 15))
ggsave("png/firearmhomicides-2018.png")
```


```{r}
SelectHomicideData_2014 <- HomicideData_2014 %>% select(state, total_murders, total_firearms) %>% mutate(year = 2014)
SelectHomicideData_2015 <- HomicideData_2015 %>% select(state, total_murders, total_firearms) %>% mutate(year = 2015)
SelectHomicideData_2016 <- HomicideData_2016 %>% select(state, total_murders, total_firearms) %>% mutate(year = 2016)
SelectHomicideData_2017 <- HomicideData_2017 %>% select(state, total_murders, total_firearms) %>% mutate(year = 2017)
SelectHomicideData_2018 <- HomicideData_2018 %>% select(state, total_murders, total_firearms) %>% mutate(year = 2018)

state <- c('Guam', 'Guam', 'Guam', 'Guam', 'Guam', 'Mariana Islands', 'Mariana Islands', 'Mariana Islands', 'Mariana Islands', 'Mariana Islands', 'Puerto Rico', 'Puerto Rico', 'Puerto Rico', 'Puerto Rico', 'Puerto Rico', 'Virgin Islands', 'Virgin Islands', 'Virgin Islands', 'Virgin Islands', 'Virgin Islands', 'Florida', 'Florida', 'Florida', 'Florida', 'Florida')
total_murders <- c(NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA)
total_firearms <- c(NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA)
year <- c(2014, 2015, 2016, 2017, 2018, 2014, 2015, 2016, 2017, 2018, 2014, 2015, 2016, 2017, 2018, 2014, 2015, 2016, 2017, 2018, 2014, 2015, 2016, 2017, 2018)
SelectExtraHomicideData <- data.frame(state, total_murders, total_firearms, year)
HomicideData <- bind_rows(list(SelectHomicideData_2014, SelectHomicideData_2015, SelectHomicideData_2016, SelectHomicideData_2017, SelectHomicideData_2018, SelectExtraHomicideData)) %>% arrange(state) 

st_crosswalk <- tibble(state = state.name) %>%
 bind_cols(tibble(abb = state.abb)) %>% 
 bind_rows(tibble(state = "District of Columbia", abb = "DC")) %>% 
 bind_rows(tibble(state = "Guam", abb = "GU")) %>% 
 bind_rows(tibble(state = "Mariana Islands", abb = "MP")) %>% 
 bind_rows(tibble(state = "Puerto Rico", abb = "PR")) %>% 
 bind_rows(tibble(state = "Virgin Islands", abb = "VI"))
HomicideData <- left_join(HomicideData, st_crosswalk, by = "state")

HomicideData
```

#2014 Homicide Data by State
```{r, fig.width = 18} 
ggplot(HomicideData, aes(x=state, y=total_firearms, fill=year)) +
  theme_modern_rc() +
  geom_boxplot(outlier.colour="red", outlier.size = 2, color="#CF592D", fill="#EFDA92") +
  scale_y_continuous(limits = c(0, 1500), breaks=seq(0, 1500, by = 100)) +
  scale_x_discrete(label=state.abb) +
  labs(x = "State", y = "Firearm Deaths", title = "Firearm Related Homicides (2014)") + 
  theme(plot.title = element_text(size = 30), text = element_text(size=25), axis.text.x = element_text(angle=90, vjust=0.5, hjust=1, size = 18), axis.text.y = element_text(hjust=1, size = 18), axis.title.x = element_text(hjust = 1, size = 25, color = "#7C9488"), axis.title.y = element_text(hjust = 1, size = 25, color = "#7C9488"), plot.caption = element_text(size = 15))
#ggsave("png/firearmhomicides-2014.png")
```


#Firearm murders stacked bar chart
```{r, fig.width = 18} 
color_table <- tibble(
  Year = c("2014", "2015", "2016", "2017", "2018"),
  Color = c("#C5ADB3", "#738E53", "#EFDA92", "#CF592D", "#246C7C")
  )
HomicideData$year <- factor(HomicideData$year, levels = color_table$Year)

ggplot(HomicideData, aes(fill=year, x=abb, y=total_firearms)) + 
  theme_modern_rc() +
  geom_bar(position=position_stack(reverse = TRUE), stat="identity", width=0.75, color="#C3C6C3") +
  scale_y_continuous(label=addUnits, limits = c(0, 7000), breaks=seq(0, 7000, by = 1000)) + 
  labs(x = "State", y = "Firearm Murders", title = "Firearm Homicides (2014 - 2018)", caption = "Includes District of Columbia (DC), Guam (GU), Mariana Islands (MP), Puerto Rico (PR), and Virgin Islands (VI).") + 
  scale_fill_manual(values=color_table$Color) + 
  theme(plot.title = element_text(size = 30), text = element_text(size=25), axis.text.x = element_text(angle=90, vjust=0.5, hjust=1, size = 18), axis.text.y = element_text(hjust=1, size = 18), axis.title.x = element_text(hjust = 1, size = 25, color = "#7C9488"), axis.title.y = element_text(hjust = 1, size = 25, color = "#7C9488"), plot.caption = element_text(size = 15))
ggsave("png/firearmhomicides_stacked_2014-2018.png")
```



#2014 Background Check Data by State
```{r, fig.width = 18} 
ggplot(BackgroundChecks_2014, aes(x=State, y=Totals)) +
  theme_modern_rc() +
  geom_bar(stat="identity") +
  scale_x_discrete(label=state.abb) +
  scale_y_continuous(label=addUnits) + 
  labs(x = "State", y = "Firearm Deaths", title = "Background Checks (2014)") + 
  theme(plot.title = element_text(size = 30), text = element_text(size=25), axis.text.x = element_text(angle=90, vjust=0.5, hjust=1, size = 18), axis.text.y = element_text(hjust=1, size = 18), axis.title.x = element_text(hjust = 1, size = 25, color = "#7C9488"), axis.title.y = element_text(hjust = 1, size = 25, color = "#7C9488"), plot.caption = element_text(size = 15))
```

#Merge background checks
```{r}
BackgroundChecks_2014 <- BackgroundChecks_2014 %>% select(State, Totals) %>% mutate(Year = 2014)
BackgroundChecks_2015 <- BackgroundChecks_2015 %>% select(State, Totals) %>% mutate(Year = 2015)
BackgroundChecks_2016 <- BackgroundChecks_2016 %>% select(State, Totals) %>% mutate(Year = 2016)
BackgroundChecks_2017 <- BackgroundChecks_2017 %>% select(State, Totals) %>% mutate(Year = 2017)
BackgroundChecks_2018 <- BackgroundChecks_2018 %>% select(State, Totals) %>% mutate(Year = 2018)

Background_Checks <- bind_rows(list(BackgroundChecks_2014, BackgroundChecks_2015, BackgroundChecks_2016, BackgroundChecks_2017, BackgroundChecks_2018)) %>% arrange(State) 

st_crosswalk <- tibble(State = state.name) %>%
 bind_cols(tibble(abb = state.abb)) %>% 
 bind_rows(tibble(State = "District of Columbia", abb = "DC")) %>% 
 bind_rows(tibble(State = "Guam", abb = "GU")) %>% 
 bind_rows(tibble(State = "Mariana Islands", abb = "MP")) %>% 
 bind_rows(tibble(State = "Puerto Rico", abb = "PR")) %>% 
 bind_rows(tibble(State = "Virgin Islands", abb = "VI"))
Background_Checks <- left_join(Background_Checks, st_crosswalk, by = "State")

Background_Checks
```

```{r}
stateAbb <- function(n) {
  labels <- ifelse(n == "Distric of Columbia", "DC",
                   state.abb)
  return(labels)
}
```


#Background check stacked bar chart
```{r, fig.width = 18} 
color_table <- tibble(
  Year = c("2014", "2015", "2016", "2017", "2018"),
  Color = c("#C5ADB3", "#738E53", "#EFDA92", "#CF592D", "#246C7C")
  )
Background_Checks$Year <- factor(Background_Checks$Year, levels = color_table$Year)

ggplot(Background_Checks, aes(fill=Year, x=abb, y=Totals)) + 
  theme_modern_rc() +
  geom_bar(position=position_stack(reverse = TRUE), stat="identity", width=0.75, color="#C3C6C3") +
  scale_y_continuous(label=addUnits, limits = c(0, 20000000), breaks=seq(0, 20000000, by = 1000000)) + 
  labs(x = "State", y = "Background Checks", title = "Background Checks (2014 - 2018)", caption = "Includes District of Columbia (DC), Guam (GU), Mariana Islands (MP), Puerto Rico (PR), and Virgin Islands (VI).") + 
  scale_fill_manual(values=color_table$Color) + 
  theme(plot.title = element_text(size = 30), text = element_text(size=25), axis.text.x = element_text(angle=90, vjust=0.5, hjust=1, size = 18), axis.text.y = element_text(hjust=1, size = 18), axis.title.x = element_text(hjust = 1, size = 25, color = "#7C9488"), axis.title.y = element_text(hjust = 1, size = 25, color = "#7C9488"), plot.caption = element_text(size = 15))
ggsave("png/backgroundchecks_stacked-2014-2018.png")
```

```{r}
pearson_correlation <- cor.test(Background_Checks$Totals, HomicideData$total_firearms, method = "pearson")
pearson_correlation
paste("Pearson Correlation coefficient: ", pearson_correlation$estimate)
paste("Pearson P value: ", pearson_correlation$p.value)

kendall_correlation <- cor.test(Background_Checks$Totals, HomicideData$total_firearms, method = "kendall")
kendall_correlation
paste("Kendall Correlation coefficient: ", kendall_correlation$estimate)
paste("Kendall P value: ", kendall_correlation$p.value)

spearman_correlation <- cor.test(Background_Checks$Totals, HomicideData$total_firearms, method = "spearman")
spearman_correlation
paste("Spearman Correlation coefficient: ", spearman_correlation$estimate)
paste("Spearman P value: ", spearman_correlation$p.value)
```

```{r}
bkchk_corr <- ggqqplot(Background_Checks$Totals, ylab = "Background Checks") + theme_modern_rc() + scale_y_continuous(label=addUnits, limits = c(-1000000, 5000000), breaks=seq(-1000000, 5000000, by = 1000000)) + 
  theme(axis.text.x = element_text(vjust=0.5, hjust=1, size = 10), axis.text.y = element_text(hjust=1, size = 10), axis.title.x = element_text(hjust = 1, size = 12, color = "#7C9488"), axis.title.y = element_text(hjust = 1, size = 12, color = "#7C9488"), plot.caption = element_text(size = 15))
homicide_corr <- ggqqplot(HomicideData$total_firearms, ylab = "Firearm Homicides") + theme_modern_rc() + 
  theme(axis.text.x = element_text(vjust=0.5, hjust=1, size = 10), axis.text.y = element_text(hjust=1, size = 10), axis.title.x = element_text(hjust = 1, size = 12, color = "#7C9488"), axis.title.y = element_text(hjust = 1, size = 12, color = "#7C9488"), plot.caption = element_text(size = 15))
cowplot::plot_grid(bkchk_corr, homicide_corr)
ggsave("png/correlation_qqplot.png")
```

