---
title: "Miniproject notebook"
output: html_notebook
# Analysis of https://www.kaggle.com/kevinzmith/honey-with-neonic-pesticide Data
# Daniel W. Anner 
---
# Load any libraries you need
```{r message=FALSE, warning=TRUE}
library(devtools)
install_github("wmurphyrd/fiftystater")

library(tidyverse)
library(readr)
library(dplyr)
library(fiftystater)
library(Hmisc)
library(viridis)
library(mapproj)
library(ggpubr)
library(ggpmisc)
library(ggrepel)
library(measurements)
setwd("E:/_Source/Stockton-DSSA/DSSA-5103_Data_Visualization/final_project")
```

# Read in the data
```{r message=FALSE, warning=TRUE}
beedata <- read_csv("HoneyBees.csv")
```

# Look at the data
```{r}
glimpse(beedata)
unique(beedata$year)
```


#Helper functions for later use
```{r message=FALSE}
# Ref: https://5harad.com/mse125/r/visualization_code.html
addUnits <- function(n) {
  labels <- ifelse(n < 1000, n,  # less than thousands
                   ifelse(n < 1e6, paste0(round(n/1e3), 'k'),  # in thousands
                          ifelse(n < 1e9, paste0(round(n/1e6), 'M'),  # in millions
                                 ifelse(n < 1e12, paste0(round(n/1e9), 'B'), # in billions
                                        ifelse(n < 1e15, paste0(round(n/1e12), 'T'), # in trillions
                                               'too big!'
                                        )))))
  return(labels)
}

getLog10 <- function(n) {
  value <- ifelse(n == 0, 0, log10(n))
}
```

```{r}
max(beedata %>% group_by(year) %>% slice(1) %>% select(year))
```


```{r}
total_pest_by_year <- beedata %>% group_by(state) %>% filter(year >= 1994 & year <= 2008) %>% mutate(nAllNeonic=conv_unit(sum(nAllNeonic, na.rm = TRUE), 'kg', 'lbs')) %>% select(state, nAllNeonic)
            total_pest_by_year
            
            plot <- ggplot(total_pest_by_year, aes(state, nAllNeonic)) + geom_bar(stat="identity") + stat_summary(fun.data=mean_cl_normal) + geom_smooth(method='lm', formula= y~x, color="black") +  scale_y_continuous(label=addUnits)
            
            plot + 
                labs(
                    title = "Total Pesticide Used",
                    subtitle = "Count of all Neonic Pesticides used",
                    caption = paste(c("Between the year of", lubridate::year(input$dateRange[1]), "and", lubridate::year(input$dateRange[2])), collapse = " ")
                ) +
                xlab("State") +
                ylab("Pounds")


  
```

```{r, fig.width = 12}
single_totals_over_all_years <- beedata %>% group_by(state) %>% transmute(totalprod=sum(totalprod)) %>% slice(1)
single_totals_over_all_years

totalprod_state_production <- ggplot(single_totals_over_all_years, aes(x=state, y=totalprod, label = single_totals_over_all_years$state)) + 
  geom_point() + 
  scale_y_continuous(label=addUnits) + 
  labs(x = "State", y = "Honey Produced (lbs)", title = "Total Honey Produced Per State 1998-2017") +
  stat_summary(fun=mean, geom="point", shape=23, size=3, fill="#EBAF4C") +
  annotate(geom = "text", x = 25, y = 658105000, label = "North Dakota: 658Mil lbs", hjust = "left") +
  annotate(geom = "text", x = 5, y = 404050000, label = "California: 404Mil lbs", hjust = "left") +
  annotate(geom = "text", x = 23, y = 220565000, label = "Montana: 220Mil lbs", hjust = "left") 

totalprod_state_production
#ggsave(
#  "total_honey_produced_1998-2017.png",
#  plot = totalprod_state_production,
#  dpi = 600
#)
```


#Boxplot of the Total Honey Produced
```{r, fig.width = 12}
boxplot <- ggplot(beedata, aes(x=state, y=totalprod)) +
  geom_jitter(alpha = 0.5, color="#fdd42d") + #aes(color = as.factor(year))) +
  geom_boxplot(outlier.color="blue", outlier.shape=4, outlier.size=4, fill="#22c1c3")  +
  scale_y_continuous(label=addUnits) + 
  labs(x = "State", y = "Honey Produced (lbs)", title = "Total Honey Produced Per State") +
  stat_summary(fun.y=mean, geom="point", shape=23, size=3, fill="tomato")
  #+ scale_colour_manual(values = rainbow(20)) 

boxplot
```

#Plot of yield per colony compared to honey produced
```{r message=FALSE}
ggplot(beedata, aes(x=yieldpercol, y=totalprod)) +
  geom_point(aes(color = state)) +
  stat_summary(fun.data=mean_cl_normal) + 
  geom_smooth(method='lm', formula= y~x, color="black") + 
  scale_y_continuous(label=addUnits) +
  labs(x = "Yield Per Colony (lbs)", y = "Honey Produced (lbs)", title = "Yield Per Colony to Honey Produced")
```


```{r message=FALSE}

```

#Transform beedata_latest
```{r message=FALSE}
beedata_latest <- beedata %>% group_by(state) %>% filter(year >= 2008 & year <= 2020) %>% mutate(nAllNeonic = (2.2 * nAllNeonic)) %>% mutate(nAllNeonic = coalesce(nAllNeonic, 0)) %>% select(state, StateName, year, nAllNeonic, totalprod)
na.omit(beedata_latest)
```

#Create our maps
```{r message=FALSE}
#USA State map
USA <- map_data("state")

#Total honey production map
totalprod_plot <-
#Total Pesticide used map
allneonic_plot <- ggplot(beedata_latest) +
  geom_map(map = fifty_states, aes(map_id = str_to_lower(StateName), fill = getLog10(nAllNeonic))) +
  labs(fill = "Total Pesticide (lbs)") +
  expand_limits(x = fifty_states$long, y = fifty_states$lat) +
  borders("state") +
  coord_map() +
  geom_text(
    data = fifty_states %>%
      group_by(id) %>%
      summarise(lat = mean(c(max(lat), min(lat))),
                long = mean(c(max(long), min(long)))) %>%
      mutate(state = id) %>%
      left_join(beedata_latest, by = c("state" = "state")),
    aes(x = long, y = lat, label = getLog10(nAllNeonic))
    ) +
  scale_fill_gradient(low="#00ff00", high="#ff7700") +
  scale_x_continuous(breaks = NULL) +
  scale_y_continuous(breaks = NULL) +
  labs(x = "", y = "", title = "Pesticide Used Per State", subtitle = "Normalized with log10") + theme(legend.position = "bottom", 
                               panel.background = element_blank())
allneonic_plot
totalprod_plot
#ggsave(
#  "pesticide_used_normalized.png",
#  plot = allneonic_plot,
#  dpi = 600
#)
#ggsave(
#  "total_honey_production_normalized.png",
#  plot = totalprod_plot,
#  dpi = 600
#)

```

#Display the maps side by side
```{r, fig.width = 12}
side_by_side <- ggpubr::ggarrange(totalprod_plot, allneonic_plot, ncol = 2, nrow = 1)
side_by_side
#ggsave(
#  "total_honey_production_pesticide_side_by_side.png",
#  plot = side_by_side,
#  dpi = 600
#)
```