#!/bin/bash
x='||||||||||||||||||||'
xLen=`printf $x | wc -m`

for arg in "$@"; do
    if [ $arg -gt $xLen ]; then
        echo "$arg is greater than $xLen"
        echo "Make sure all values are less than or equal to 20"
        exit
    fi
done

echo "|---5----10---15---20---25--->"
echo $x | cut -c1-$1
echo $x | cut -c1-$2
echo $x | cut -c1-$3
echo $x | cut -c1-$4
echo $x | cut -c1-$5
echo "|---5----10---15---20---25--->"
